watch: true
schema: './graphql/schema.graphql'
documents: './graphql/**/!(*.d).{ts,tsx,graphql}'
generates:
  ./graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        func: '../hooks/useShopifyApi#useShopifyApi'
        isReactHook: true